### ISSUE TITLE
Naming of the method

### ISSUE THREAD

**Issue by abozhilov** [tc39/proposal-string-matchall#8]
With latest semantic changes, the name should be changed too https://github.com/tc39/String.prototype.matchAll/issues/6.

``` javascript
while (match = /abc/g.exec(str)) {
    //Processing next match    
}
```

This is very common pattern to processing separately each matching. I think the name should match the pattern above. I'd like to propose: 

`RegExp.prototype.execIterator`

**Comment by WebReflection** [comment]
Anything but `All` as suffix please, 'cause an iterator doesn't necessarily have to iterate all matches and, being an iterator, it doesn't necessarily have to be a finite list.

Accordingly, suffixing anything that is used in a `for/of` with `All` would me misleading so please change this name  into anything else that makes more sense and, eventually, propose TC39 to  never use `All` as suffix for anything related to iterations via `for/of`

Thank you

**Comment by ljharb** [comment]
I doubt that an "Iterator" suffix will ever fly - that's just too cumbersome and ridiculous.

@WebReflection do you have an atlernative suggestion? `for (const match of str.matchAll(regex)) { … }` doesn't seem problematic to me.

**Comment by WebReflection** [comment]
like I've said, `All` is misleading and, as such problematic.

It's not `All` ... its maybe all, so it fails as a name for its intent. All would be something that returns directly All matches, an iteration is never `All` unless fully consumed.

Reading your comment in the other thread, you also said you like `nouns` but not verbs ... here you are  proposing an action through the verb `match`,  and a misleading one because it's not necessarily true that it's going to be all.

To me `matches` is also non problematic as noun,  a `match` in `matches` like an `entry` in `entries` and a `value` in `values` ... none of them is necessarily `All` and all describes what kind of value the iteration will return.

Since this for some reason `matches` doesn't work (I mean,  even `value` is a verb and nobody complained there?) I'm struggling to find anything which purpose is to describe exactly what `matches` does already.

If I come up with a better name, I'll propose it.

**Comment by ljharb** [comment]
it's an iterator for "all matches" - "all" has nothing to do with the iteration, and I'm not familiar with any "all" naming convention as it relates to iterators that would imply that "all" means the iterator is fully consumed. The name "matches" also doesn't say "all" but it's implied, regardless of whether you consumer all the iterations or not.

Thanks, I look forward to future suggestions!

**Comment by WebReflection** [comment]
> it's an iterator for "all matches" 

that's my exact point. You end up describing it as `matches` so any different name would be less meaningful.

Again,  `value` is a verb so the argument `verb` and `noun

**Comment by RReverser** [comment]
@ljharb Btw, if the only concern about `matches` is that it's `verb` and `noun` at the same time, we can always go with `listMatches` or `getMatches` :smile:

**Comment by RReverser** [comment]
However `matchAll` is fine to me too.

>  'cause an iterator doesn't necessarily have to iterate all matches and, being an iterator, it doesn't necessarily have to be a finite list

This doesn't really reply to immutable structures as strings - it returns iterator to all matches, and it's definitely finite, and only consumer decides how much he wants to take ("slice") out of it.

**Comment by WebReflection** [comment]
not necessarily, so since `matchSome` could happen as well as `matchNone` if there's no match, having a suffix that is different from any other iterator name doesn't look like the right decision to me.

It's a precedent, quite unnecessary, and, as usual in the history of JS ... inconsistent with what already there.

**Comment by ljharb** [comment]
This is a method that has no precedent in JS. All the existing iterator-returning methods take no arguments and return a different iterator over `this`. This one takes an argument and uses it to iterate over `this`. "what's already there" arguments aren't going to carry very much weight here.

**Comment by WebReflection** [comment]
it's about having a precedent with a bad naming  convention  indeed.

Ironically, I wouldn't mind `allMatches` so at least sounds more semantic in a `for(let match of reg.allMatches(string))`

I can't actually think of anything else.

**Comment by allenwb** [comment]
I like `matches`.   It follows the precedent set by `keys`, `values`, `entries` that an iterator is named using a pluralized noun that is descriptive of the value returned by the interator's `next` call.

**Comment by ljharb** [comment]
So far `matchAll`, `matches`, and `allMatches` are what's still on the table then so far. There were a number of people of the opinion that "matches" seems like it should return a boolean, but if the committee prefers it, that'd be fine too.

**Comment by ljharb** [comment]
@WebReflection it'd be `string.allMatches(reg)` but i do see the point that that sounds more like a noun than `matchAll` in that specific context.

**Comment by WebReflection** [comment]
like @allenwb said, I wish `matches` was the pick, but if the consistent direction is to prefer nouns for iterators than I'm happy it's `allMatches` instead of `matchAll` ... but if think myself writing it ... I gonna repeat myself saying I wish it was just `matches`

**Comment by RReverser** [comment]
`allMatches`? Please don't. All the arguments about "not necessarily all matches" still apply, except that when it was not-a-noun `matchAll`, we could at least consider that it "does match all" but does not necessarily return all of them (since it's iterator), while `allMatches` sounds like it does return "all matches" at once.

Personally, I'm for `matches` too or at least keeping as-is.

**Comment by WebReflection** [comment]
yeah, my `allMatches` proposal wasn't a definitive one, was just about covering the `noun` part without having an `All` suffix for the same reasons you explained.

Let's have a twitter poll :D

**Comment by RReverser** [comment]
> Let's have a twitter poll :D

Haha, @bterlson would love it!

**Comment by WebReflection** [comment]
I know, retweet, vote, and share?
https://twitter.com/WebReflection/status/668933099913388033

Maybe useful to understand between second and third at least, if the first is really not an option.

**Comment by RReverser** [comment]
"that will iterator" such a mistype after talks about noun vs verbs :smile: 
(also I would explicitly note that this is for regular expression matches)

**Comment by WebReflection** [comment]
changed the link above

**Comment by WebReflection** [comment]
FYI and FWIW the poll result

![screenshot from 2015-11-24 23-37-48](https://cloud.githubusercontent.com/assets/85749/11382845/8f1e07fe-9304-11e5-8b00-c6f712412528.png)

**Comment by ljharb** [comment]
Pending further committee feedback (the next time I present this), we're sticking with `matchAll`.
